apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth 
  template:
    metadata:
      labels:
        app: auth 
    spec:
      containers:
        - name: auth 
          image: furkanh/ecommerce-auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-service:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth 
  ports:
    - name: auth 
      protocol: TCP
      port: 3000
      targetPort: 3000